//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsSubject
    {
        public int code { get; set; }
        public int SubjectId { get; set; }
        public int ItemId { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
