//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.ItemsSubject = new HashSet<ItemsSubject>();
        }
    
        public int ItemId { get; set; }
        public int ItemKind { get; set; }
        public string ContextUrl { get; set; }
        public string ItemName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> VisitedCounter { get; set; }
        public string ImgUrl { get; set; }
        public bool EnableSearch { get; set; }
    
        public virtual Kinds Kinds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsSubject> ItemsSubject { get; set; }
    }
}
