//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordLocation
    {
        public int ID { get; set; }
        public int BookSenteceID { get; set; }
        public Nullable<int> SearchId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int Counter { get; set; }
    
        public virtual BookPages BookPages { get; set; }
        public virtual PreSearches PreSearches { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
